#!/usr/bin/env bash
# Copyright 2017-2020 by SDRausty. All rights reserved, see LICENSE 🌎 🌍 🌏
# Hosting sdrausty.github.io/TermuxArch courtesy https://pages.github.com.
# https://sdrausty.github.io/TermuxArch/README has info about this project.
# https://sdrausty.github.io/TermuxArch/CONTRIBUTORS Thank you for your help.
##############################################################################
# IFS=$'\n\t'
set -Eeuo pipefail
shopt -s nullglob globstar
unset LD_PRELOAD
VERSIONID=2.0.880
 
_TRPERR_() {  # run on script error
	local RV="$?"
	printf "\\e[?25h\\n\\e[1;48;5;138m %s\\e[0m\\n\\n" "TermuxArch WARNING:  Generated script signal ${RV:-UNKNOWN} near or at line number ${1:-UNKNOWN} by '${2:-COMMAND}'!"
	exit 201
}
 
_TRPET_() {  # run on exit
	local RV="$?" 
	printf "" 
	 
	if [[ "$RV" = 0 ]]
	then
		printf "\\e[0;32m%s\\e[1;34m: \\e[1;32m%s\\e[0m\\n\\e[0m" "${0##*/} $@ $VERSIONID" "DONE 🏁 "
		printf "\\e]2; %s: %s \007" "${0##*/} $@" "DONE 🏁 "
	else 
		printf "\\e[0;32m%s \\e[0m%s\\e[1;34m: \\e[1;32m%s\\e[0m\\n\\e[0m" "${0##*/} $@ $VERSIONID" "[Exit Signal $RV]" "DONE  🏁 "
		printf "\033]2; %s: %s %s \007" "${0##*/} $@" "[Exit Signal $RV]" "DONE 🏁 "
	fi
	printf "\e[?25h\e[0m"
	set +Eeuo pipefail
	exit
}
 
_TRPSIG_() {  # run on signal
	printf "\\e[?25h\\e[1;7;38;5;0mTermuxArch WARNING:  Signal $? received!\\e[0m\\n"
	exit 211
}
 
_TRPQ_() {  # run on quit
	printf "\\e[?25h\\e[1;7;38;5;0mTermuxArch WARNING:  Quit signal $? received!\\e[0m\\n"
	exit 221
}
 
trap '_TRPERR_ $LINENO $BASH_COMMAND $?' ERR
trap _TRPET_ EXIT
trap _TRPSIG_ HUP INT TERM
trap _TRPQ_ QUIT
 
units="$(df 2>/dev/null | awk 'FNR == 1 {print $2}')"
DFDATA="$(df 2>/dev/null)"
if [[ $DFDATA =~ .*/data.* ]]
then
   echo "I found a word faq in {url}."
echo data
USRSPACE="$(df 2>/dev/null | grep "/data" | awk {'print $4'})"
else
   echo "Sorry. Not found."
echo slash
USRSPACE="$(df 2>/dev/null | grep -w "/" | awk {'print $4'})"
fi
# echo $DFDATA
# exit
# if [[ -z "${DFDATA:-}" ]]
# # if "$(df 2>/dev/null | grep '/data')"
# then
# echo slash
# USRSPACE="$(df 2>/dev/null | grep -w "/" | awk {'print $4'})"
# else
# echo data
# USRSPACE="$(df 2>/dev/null | grep "/data" | awk {'print $4'})"
# fi
printf "\\e[0;33m%s\\n\\e[0m" "$USRSPACE $units of free user space is available on this device."
# dfa EOF
