<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://termuxarch.github.io/TermuxArch/</loc>
    <lastmod>2020-09-03</lastmod>
  </url>
  <url>
    <loc>https://termuxarch.github.io/TermuxArch/setupTermuxArch</loc>
    <lastmod>2020-09-03</lastmod>
  </url>
  <url>
    <loc>https://termuxarch.github.io/TermuxArch/CONTRIBUTORS.html</loc>
    <lastmod>2020-09-03</lastmod>
  </url>
  <url>
    <loc>https://termuxarch.github.io/TermuxArch/NOTICE.html</loc>
    <lastmod>2020-09-03</lastmod>
  </url>
  <url>
    <loc>https://termuxarch.github.io/TermuxArch/NOTICE</loc>
    <lastmod>2020-09-03</lastmod>
  </url>
  <url>
    <loc>https://termuxarch.github.io/TermuxArch/docs/PRoot</loc>
    <lastmod>2020-09-03</lastmod>
  </url>
  <url>
    <loc>https://termuxarch.github.io/TermuxArch/docs/Arch</loc>
    <lastmod>2020-09-03</lastmod>
  </url>
  <url>
    <loc>https://termuxarch.github.io/TermuxArch/docs/install</loc>
    <lastmod>2020-09-03</lastmod>
  </url>
  <url>
    <loc>https://termuxarch.github.io/TermuxArch/docs/README.md</loc>
    <lastmod>2020-09-03</lastmod>
  </url>
  <url>
    <loc>https://termuxarch.github.io/TermuxArch/docs/TermuxSetupStorage</loc>
    <lastmod>2020-09-03</lastmod>
  </url>
</urlset>